In [3]:
import numpy as np
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

res1 = np.dot(v1,v2)
res2 = np.dot(v2,v1)

print(res1)
print(res2)


130
130


In [15]:
mat1 = np.random.randint(1,10,(4,6))
mat2 = np.random.randint(1,10,(4,6))
print(mat1)
print(" ")
print(mat2)

[[5 5 7 9 5 7]
 [3 6 1 4 8 3]
 [1 1 3 6 9 4]
 [5 3 7 1 8 8]]
 
[[1 5 4 1 8 2]
 [6 7 8 3 3 3]
 [4 5 5 8 2 4]
 [1 5 3 9 9 7]]


In [19]:
arr = np.zeros(mat1.shape[1])
for i in range(mat1.shape[1]):
    arr[i] = np.dot(mat1[:,i],mat2[:,i])

arr
    

array([ 32.,  87.,  72.,  78., 154.,  95.])

In [23]:
vec1 = np.random.randint(1,10,(2))
vec2 = np.random.randint(1,10,(2))

print(vec1)
print(vec2)

res1 = np.dot(vec1,vec2)
res2 = np.dot(vec2,vec1)

con = bool(res1 == res2)
con



[4 9]
[9 7]


True

In [25]:
vec = np.array([2,3])
dot = np.dot(vec,vec)
length = np.sqrt(dot)
print(dot)
length

13


3.605551275463989

In [41]:
vec1 = np.random.randn(3)
vec2 = np.random.randn(3)

scalar = -2
res1 = np.dot(vec1,vec2)
res2 = np.dot(vec1*scalar,vec2*scalar)
print(res1)
print(res2)
bool(np.sign(res1) == np.sign(res2))

#the sign of the dot product is invariant to scalar multiplication





1.5369634774203733
6.147853909681493


True

In [44]:
mat1 = np.random.randint(1,10,(3,3))
mat2 = np.random.randint(1,10,(3,3))

print(mat1)
print(" ")
print(mat2)

scalar = 2
res1 = mat1*scalar + mat2*scalar
res2 = scalar * (mat1 + mat2)
print(" ")

print(res1)
print(" ")
print(res2)





[[5 4 6]
 [4 7 2]
 [1 2 1]]
 
[[6 9 8]
 [8 1 8]
 [3 8 8]]
 
[[22 26 28]
 [24 16 20]
 [ 8 20 18]]
 
[[22 26 28]
 [24 16 20]
 [ 8 20 18]]


In [51]:
M1 = np.round(6*np.random.randn(4,4))
M2 = np.round(6*np.random.randn(4,4))

tr1 = np.trace(M1 + M2)
tr2 = np.trace(M1) + np.trace(M2)
bool(tr1 == tr2)



True

In [32]:
import numpy as np
mat1 = np.random.randint(1,10,(2,2))
mat2 = np.random.randint(1,10,(2,2))

print(mat1)
print(" ")
print(mat2)



[[5 7]
 [3 3]]
 
[[7 3]
 [9 6]]


In [33]:
np.matmul(mat1,mat2)


array([[98, 57],
       [48, 27]])

In [34]:

def matrix_multiply(matrix1, matrix2):
    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("Matrices dimensions are not appropriate for multiplication")
    
    result = np.zeros((matrix1.shape[0], matrix2.shape[1]))
    
    for i in range(matrix1.shape[1]):
        column = matrix1[:, i:i+1]
        for j in range(matrix2.shape[1]):
            result[:, j:j+1] += column * matrix2[i, j]
    
    return result

# Example usage
result = matrix_multiply(mat1, mat2)
print("Result of custom matrix multiplication:")
print(result)

# Verify with numpy's matmul
print("\nVerification with numpy's matmul:")
print(np.matmul(mat1, mat2))

# Check if results are equal
print("\nResults are equal:", np.allclose(result, np.matmul(mat1, mat2)))




Result of custom matrix multiplication:
[[98. 57.]
 [48. 27.]]

Verification with numpy's matmul:
[[98 57]
 [48 27]]

Results are equal: True
